# command line: main.py

base_lr: 0.05
batch_size: 2
config: E:/pymprojects/Hyper-GCN-main/Hyper-GCN-main/config/base/nturgbd-cross-subject/hyper_joint.yaml
device:
- 0
eval_epoch: 55
eval_interval: 5
feeder: feeders.feeder_ntu.Feeder
ignore_weights: []
log_interval: 100
lr_decay_rate: 0.1
model: model.hypergcn_base.Model
model_args:
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: spatial
    use_hyper_prior: true
  hyper_joints: 0
  num_class: 60
  num_person: 2
  num_point: 25
model_saved_name: ''
nesterov: true
num_epoch: 140
num_worker: 4
optimizer: SGD
pas_config:
  early_conf_threshold: 0.15
  early_epochs: 30
  early_prior_weight: 0.7
  early_sem_weight: 0.3
  mid_conf_threshold: 0.25
  mid_epochs: 80
  mid_prior_weight: 0.4
  mid_sem_weight: 0.6
phase: train
print_log: true
save_epoch: 110
save_interval: 1
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 110
- 120
test_batch_size: 2
test_feeder_args:
  bone: false
  data_path: E:\pymprojects\data\ntu\NTU60_CS.npz
  debug: false
  p_interval:
  - 0.95
  split: test
  vel: false
  window_size: 64
train_feeder_args:
  bone: false
  data_path: E:\pymprojects\data\ntu\NTU60_CS.npz
  debug: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: false
  random_rot: true
  random_shift: false
  split: train
  vel: false
  window_size: 64
warm_up_epoch: 5
weight_decay: 0.0004
weights: null
work_dir: ./work_dir/ntu60/xsub/joint
