work_dir: ./work_dir/ntu60/xsub/joint

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: data/NTU60_CS.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: data/NTU60_CS.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.hypergcn_large.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  hyper_joints: 3
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'virtual_ensemble'

#optim
weight_decay: 0.0004
base_lr: 0.05
lr_decay_rate: 0.1
step: [110, 120]
warm_up_epoch: 5

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 140
save_epoch: 110
nesterov: True
